=== trifork/bemyndigelsesregister/bemyndigelsesservice/src/main/resources/schema/2016_01_01/bemyndigelsesservice.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema version="2.0" targetNamespace="http://nsi.dk/bemyndigelse/2016/01/01/"
           xmlns:cpr="http://rep.oio.dk/cpr.dk/xml/schemas/core/2005/03/18/"
           xmlns:cvr="http://rep.oio.dk/cvr.dk/xml/schemas/2005/03/22/"
           xmlns:bms20160101="http://nsi.dk/bemyndigelse/2016/01/01/"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:import namespace="http://rep.oio.dk/cpr.dk/xml/schemas/core/2005/03/18/" schemaLocation="../CPR_PersonCivilRegistrationIdentifier.xsd"/>
    <xs:import namespace="http://rep.oio.dk/cvr.dk/xml/schemas/2005/03/22/" schemaLocation="../CVR_CVRnumberIdentifier.xsd"/>

    <xs:complexType name="Bemyndigelse">
        <xs:sequence>
            <xs:element name="BemyndigelseKode" type="bms20160101:BemyndigelseKode"/>
            <xs:element name="BemyndigendeCpr" type="cpr:PersonCivilRegistrationIdentifierType"/>
            <xs:element name="BemyndigedeCpr" type="cpr:PersonCivilRegistrationIdentifierType"/>
            <xs:element name="BemyndigedeCvr" type="cvr:CVRnumberIdentifierType" minOccurs="0"/>
            <xs:element name="System" type="bms20160101:System"/>
            <xs:element name="SystemLangtNavn" type="bms20160101:SystemLangtNavn"/>
            <xs:element name="Arbejdsfunktion" type="bms20160101:Arbejdsfunktion"/>
            <xs:element name="Status" type="bms20160101:Status"/>
            <xs:element name="RettighedNavnBeskrivelse" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="RettighedNavn" type="bms20160101:RettighedNavn"/>
                        <xs:element name="RettighedBeskrivelse" type="bms20160101:RettighedBeskrivelse"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="Oprettelsesdato" type="xs:dateTime"/>
            <xs:element name="Gyldig_fra" type="xs:dateTime"/>
            <xs:element name="Gyldig_til" type="xs:dateTime"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Arbejdsfunktioner">
        <xs:sequence>
            <xs:element name="Arbejdsfunktion" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="Domaene" type="bms20160101:Domaene"/>
                        <xs:element name="System" type="bms20160101:System"/>
                        <xs:element name="ArbejdsfunktionNavn" type="bms20160101:ArbejdsfunktionNavn"/>
                        <xs:element name="ArbejdsfunktionBeskrivelse" type="bms20160101:ArbejdsfunktionBeskrivelse"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Rettigheder">
        <xs:sequence>
            <xs:element name="Rettighed" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="Domaene" type="bms20160101:Domaene"/>
                        <xs:element name="System" type="bms20160101:System"/>
                        <xs:element name="RettighedNavn" type="bms20160101:RettighedNavn"/>
                        <xs:element name="RettighedBeskrivelse" type="bms20160101:RettighedBeskrivelse"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="DelegerbareRettigheder">
        <xs:sequence>
            <xs:element name="DelegerbarRettighed" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="Domaene" type="bms20160101:Domaene"/>
                        <xs:element name="System" type="bms20160101:System"/>
                        <xs:element name="Arbejdsfunktion" type="bms20160101:Arbejdsfunktion"/>
                        <xs:element name="RettighedNavn" type="bms20160101:RettighedNavn"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="BemyndigelseKode">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>
    <xs:simpleType name="Domaene">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>
    <xs:simpleType name="System">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>
    <xs:simpleType name="SystemLangtNavn">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>
    <xs:simpleType name="Arbejdsfunktion">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>
    <xs:simpleType name="RettighedNavn">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>
    <xs:simpleType name="RettighedBeskrivelse">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>
    <xs:simpleType name="ArbejdsfunktionNavn">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>
    <xs:simpleType name="ArbejdsfunktionBeskrivelse">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>
    <xs:simpleType name="Status">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Anmodet"/>
            <xs:enumeration value="Oprettet"/>
        </xs:restriction>
    </xs:simpleType>


    <xs:element name="IndlaesMetadataRequest">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Domaene" type="bms20160101:Domaene"/>
                <xs:element name="System" type="bms20160101:System"/>
                <xs:element name="SystemLangtNavn" type="bms20160101:SystemLangtNavn"/>
                <xs:element name="Arbejdsfunktioner" type="bms20160101:Arbejdsfunktioner"/>
                <xs:element name="Rettigheder" type="bms20160101:Rettigheder" minOccurs="0"/>
                <xs:element name="DelegerbareRettigheder" type="bms20160101:DelegerbareRettigheder" minOccurs="0"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="IndlaesMetadataResponse">
        <xs:complexType>
            <xs:sequence/>
        </xs:complexType>
    </xs:element>

    <xs:element name="HentMetadataRequest">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Domaene" type="xs:string"/>
                <xs:element name="System" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="HentMetadataResponse">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Domaene" type="bms20160101:Domaene"/>
                <xs:element name="System" type="bms20160101:System"/>
                <xs:element name="SystemLangtNavn" type="bms20160101:SystemLangtNavn"/>
                <xs:element name="Arbejdsfunktioner" type="bms20160101:Arbejdsfunktioner" minOccurs="0"/>
                <xs:element name="Rettigheder" type="bms20160101:Rettigheder" minOccurs="0"/>
                <xs:element name="DelegerbarRettigheder" type="bms20160101:DelegerbareRettigheder" minOccurs="0"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="OpretBemyndigelserRequest">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="10" minOccurs="1" name="Oprettelse">
                    <xs:complexType>
                        <xs:all>
                            <xs:element name="BemyndigendeCpr" type="cpr:PersonCivilRegistrationIdentifierType"/>
                            <xs:element name="BemyndigedeCpr" type="cpr:PersonCivilRegistrationIdentifierType"/>
                            <xs:element name="BemyndigedeCvr" type="cvr:CVRnumberIdentifierType" minOccurs="0"/>
                            <xs:element name="System" type="bms20160101:System"/>
                            <xs:element name="Arbejdsfunktion" type="bms20160101:Arbejdsfunktion"/>
                            <xs:element name="Status" type="bms20160101:Status"/>
                            <xs:element name="RettighedNavne">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element maxOccurs="unbounded" minOccurs="1" name="RettighedNavn" type="bms20160101:RettighedNavn"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element maxOccurs="1" minOccurs="0" name="GyldigFra" type="xs:dateTime"/>
                            <xs:element maxOccurs="1" minOccurs="0" name="GyldigTil" type="xs:dateTime"/>
                        </xs:all>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="OpretBemyndigelserResponse">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Bemyndigelse" type="bms20160101:Bemyndigelse" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="HentBemyndigelserRequest">
        <xs:complexType>
            <xs:choice>
                <xs:element name="BemyndigendeCpr" type="cpr:PersonCivilRegistrationIdentifierType"/>
                <xs:element name="BemyndigedeCpr" type="cpr:PersonCivilRegistrationIdentifierType"/>
                <xs:element name="BemyndigelseKode" type="bms20160101:BemyndigelseKode"/>
            </xs:choice>
        </xs:complexType>
    </xs:element>

    <xs:element name="HentBemyndigelserResponse">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Bemyndigelse" type="bms20160101:Bemyndigelse" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="SletBemyndigelserRequest">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="BemyndigelseKode" type="bms20160101:BemyndigelseKode" maxOccurs="unbounded"/>
                <xs:element name="Slettedato" type="xs:dateTime"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="SletBemyndigelserResponse">
        <xs:complexType>
            <xs:sequence>
                    <xs:element name="BemyndigelseKode" type="bms20160101:BemyndigelseKode" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== trifork/bemyndigelsesregister/bemyndigelsesservice/src/test/examples/2016_01_01/HentBemyndigelserResponse.xml
<?xml version="1.0" encoding="UTF-8"?>
<bms20160101:HentBemyndigelserResponse
        xmlns:bms20160101="http://nsi.dk/bemyndigelse/2016/01/01/"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://nsi.dk/bemyndigelse/2016/01/01 ../../../main/resources/schema/2016_01_01/bemyndigelsesservice.xsd">
    <Bemyndigelse>
        <BemyndigelseKode>9DD1BC7E-76AF-43BC-9C2C-ABAE4257E64F</BemyndigelseKode>
        <BemyndigendeCpr>2005511871</BemyndigendeCpr>
        <BemyndigedeCpr>0304838140</BemyndigedeCpr>
        <BemyndigedeCvr>20921897</BemyndigedeCvr>
        <System>FMK</System>
        <SystemLangtNavn>Fælles Medicinkort</SystemLangtNavn>
        <Arbejdsfunktion>Læge</Arbejdsfunktion>
        <Status>Oprettet</Status>
        <RettighedNavnBeskrivelse>
            <RettighedNavn>SundhedsfagligOpslag</RettighedNavn>
            <RettighedBeskrivelse>Sundhedsfagligt opslag</RettighedBeskrivelse>
        </RettighedNavnBeskrivelse>
        <Oprettelsesdato>2016-01-04T10:10:00Z</Oprettelsesdato>
        <Gyldig_fra>2016-02-01T00:00:00Z</Gyldig_fra>
        <Gyldig_til>2017-01-31T00:00:00Z</Gyldig_til>
    </Bemyndigelse>
    <Bemyndigelse>
        <BemyndigelseKode>DB83CA88-2B84-4ADE-908F-596F9ABE366C</BemyndigelseKode>
        <BemyndigendeCpr>2005511871</BemyndigendeCpr>
        <BemyndigedeCpr>0304838140</BemyndigedeCpr>
        <System>DDV</System>
        <SystemLangtNavn>Vaccinationsregistret</SystemLangtNavn>
        <Arbejdsfunktion>Læge</Arbejdsfunktion>
        <Status>Oprettet</Status>
        <RettighedNavnBeskrivelse>
            <RettighedNavn>VaccinationVedligehold</RettighedNavn>
            <RettighedBeskrivelse>Opret, ret eller slet vaccinationer</RettighedBeskrivelse>
        </RettighedNavnBeskrivelse>
        <RettighedNavnBeskrivelse>
            <RettighedNavn>VaccinationVedligeholdAnbefalet</RettighedNavn>
            <RettighedBeskrivelse>Opret, ret eller slet anbefalede vaccinationer</RettighedBeskrivelse>
        </RettighedNavnBeskrivelse>
        <Oprettelsesdato>2016-01-04T10:10:00Z</Oprettelsesdato>
        <Gyldig_fra>2016-01-04T10:10:00Z</Gyldig_fra>
        <Gyldig_til>2017-01-31T00:00:00Z</Gyldig_til>
    </Bemyndigelse>
    <Bemyndigelse>
        <BemyndigelseKode>2079412A-FC09-4072-A5DA-039B80357369</BemyndigelseKode>
        <BemyndigendeCpr>2005511871</BemyndigendeCpr>
        <BemyndigedeCpr>0304838140</BemyndigedeCpr>
        <System>TAS</System>
        <SystemLangtNavn>Tilskudsansøgningsservicen</SystemLangtNavn>
        <Arbejdsfunktion>Læge</Arbejdsfunktion>
        <Status>Oprettet</Status>
        <RettighedNavnBeskrivelse>
            <RettighedNavn>*</RettighedNavn>
            <RettighedBeskrivelse>Alle nuværende og fremtidige delegerbare rettigheder</RettighedBeskrivelse>
        </RettighedNavnBeskrivelse>
        <Oprettelsesdato>2016-01-04T10:10:00Z</Oprettelsesdato>
        <Gyldig_fra>2016-01-04T10:10:00Z</Gyldig_fra>
        <Gyldig_til>2017-01-04T10:10:00Z</Gyldig_til>
    </Bemyndigelse>
</bms20160101:HentBemyndigelserResponse>

=== trifork/bemyndigelsesregister/bemyndigelsesservice/src/test/examples/2016_01_01/OpretBemyndigelserRequest.xml
<?xml version="1.0" encoding="UTF-8"?>
<bms20160101:OpretBemyndigelserRequest
        xmlns:bms20160101="http://nsi.dk/bemyndigelse/2016/01/01/"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://nsi.dk/bemyndigelse/2016/01/01 ../../../main/resources/schema/2016_01_01/bemyndigelsesservice.xsd">
    <Oprettelse>
        <BemyndigendeCpr>2005511871</BemyndigendeCpr>
        <BemyndigedeCpr>0304838140</BemyndigedeCpr>
        <BemyndigedeCvr>20921897</BemyndigedeCvr>
        <System>FMK</System>
        <Arbejdsfunktion>Læge</Arbejdsfunktion>
        <Status>Oprettet</Status>
        <RettighedNavne>
            <RettighedNavn>SundhedsfagligtOpslag</RettighedNavn>
        </RettighedNavne>
        <GyldigFra>2016-02-01T00:00:00Z</GyldigFra>
        <GyldigTil>2017-01-31T00:00:00Z</GyldigTil>
    </Oprettelse>
    <Oprettelse>
        <BemyndigendeCpr>2005511871</BemyndigendeCpr>
        <BemyndigedeCpr>0304838140</BemyndigedeCpr>
        <System>DDV</System>
        <Arbejdsfunktion>Læge</Arbejdsfunktion>
        <Status>Oprettet</Status>
        <RettighedNavne>
            <RettighedNavn>VaccinationVedligehold</RettighedNavn>
            <RettighedNavn>VaccinationVedligeholdAnbefalet</RettighedNavn>
        </RettighedNavne>
        <GyldigTil>2017-01-31T00:00:00Z</GyldigTil>
    </Oprettelse>
    <Oprettelse>
        <BemyndigendeCpr>2005511871</BemyndigendeCpr>
        <BemyndigedeCpr>0304838140</BemyndigedeCpr>
        <System>TAS</System>
        <Arbejdsfunktion>Læge</Arbejdsfunktion>
        <Status>Oprettet</Status>
        <RettighedNavne>
            <RettighedNavn>*</RettighedNavn>
        </RettighedNavne>
    </Oprettelse>
</bms20160101:OpretBemyndigelserRequest>

=== trifork/bemyndigelsesregister/bemyndigelsesservice/src/test/examples/2016_01_01/IndlaesMetadataRequest.xml
<?xml version="1.0" encoding="UTF-8"?>
<bms20160101:IndlaesMetadataRequest
        xmlns:bms20160101="http://nsi.dk/bemyndigelse/2016/01/01/"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://nsi.dk/bemyndigelse/2016/01/01 ../../../main/resources/schema/2016_01_01/bemyndigelsesservice.xsd">
    <System>TAS</System>
    <SystemLangtNavn>Tilskudsansøgningsservicen</SystemLangtNavn>
    <Arbejdsfunktioner>
        <Arbejdsfunktion>
            <Domaene>SST</Domaene>
            <System>TAS</System>
            <ArbejdsfunktionNavn>Læge</ArbejdsfunktionNavn>
            <ArbejdsfunktionBeskrivelse>Autoriseret læge</ArbejdsfunktionBeskrivelse>
        </Arbejdsfunktion>
        <Arbejdsfunktion>
            <Domaene>SST</Domaene>
            <System>TAS</System>
            <ArbejdsfunktionNavn>Tandlæge</ArbejdsfunktionNavn>
            <ArbejdsfunktionBeskrivelse>Autoriseret tandlæge</ArbejdsfunktionBeskrivelse>
        </Arbejdsfunktion>
    </Arbejdsfunktioner>
    <Rettigheder>
        <Rettighed>
            <Domaene>SST</Domaene>
            <System>TAS</System>
            <RettighedNavn>LæsAnsøgninger</RettighedNavn>
            <RettighedBeskrivelse>Vise indsendte tilskudsansøgninger</RettighedBeskrivelse>
        </Rettighed>
        <Rettighed>
            <Domaene>SST</Domaene>
            <System>TAS</System>
            <RettighedNavn>SkrivAnsøgninger</RettighedNavn>
            <RettighedBeskrivelse>Oprette tilskudsansøgninger og svare på yderligere oplysninger</RettighedBeskrivelse>
        </Rettighed>
    </Rettigheder>
    <DelegerbareRettigheder>
        <DelegerbarRettighed>
            <Domaene>SST</Domaene>
            <System>TAS</System>
            <Arbejdsfunktion>Læge</Arbejdsfunktion>
            <RettighedNavn>LæsAnsøgninger</RettighedNavn>
        </DelegerbarRettighed>
        <DelegerbarRettighed>
            <Domaene>SST</Domaene>
            <System>TAS</System>
            <Arbejdsfunktion>Tandlæge</Arbejdsfunktion>
            <RettighedNavn>LæsAnsøgninger</RettighedNavn>
        </DelegerbarRettighed>
    </DelegerbareRettigheder>
</bms20160101:IndlaesMetadataRequest>
